In [1]:
import pandas as pd
import numpy as np

In [5]:
df = pd.read_csv('data/hacker_news.csv')
print(df.head())

         id                                              title  \
0  12224879                          Interactive Dynamic Video
1  11964716  Florida DJs May Face Felony for April Fools' W...
2  11919867       Technology ventures: From Idea to Enterprise
3  10301696  Note by Note: The Making of Steinway L1037 (2007)
4  10482257  Title II kills investment? Comcast and other I...

                                                 url  num_points  \
0            http://www.interactivedynamicvideo.com/         386
1  http://www.thewire.com/entertainment/2013/04/f...           2
2  https://www.amazon.com/Technology-Ventures-Ent...           3
3  http://www.nytimes.com/2007/11/07/movies/07ste...           8
4  http://arstechnica.com/business/2015/10/comcas...          53

   num_comments      author       created_at
0            52    ne0phyte   8/4/2016 11:52
1             1    vezycash  6/23/2016 22:20
2             1     hswarna   6/17/2016 0:01
3             2  walterbell   9/30/2015 4:12
4            22      Deinos  10/31/2015 9:48

In [9]:
df.tail()

,id,title,url,num_points,num_comments,author,created_at
20093,12379592,How Purism Avoids Intels Active Management Tec...,https://puri.sm/philosophy/how-purism-avoids-i...,10,6,AdmiralAsshat,8/29/2016 2:22
20094,10339284,YC Application Translated and Broken Down,https://medium.com/@zreitano/the-yc-applicatio...,4,1,zreitano,10/6/2015 14:57
20095,10824382,Microkernels are slow and Elvis didn't do no d...,http://blog.darknedgy.net/technology/2016/01/0...,169,132,vezzy-fnord,1/2/2016 0:49
20096,10739875,How Product Hunt really works,https://medium.com/@benjiwheeler/how-product-h...,695,222,brw12,12/15/2015 19:32
20097,11680777,RoboBrowser: Your friendly neighborhood web sc...,https://github.com/jmcarp/robobrowser,182,58,pmoriarty,5/12/2016 1:43

In [12]:
title = df['title']
title

0                                Interactive Dynamic Video
1        Florida DJs May Face Felony for April Fools' W...
2             Technology ventures: From Idea to Enterprise
3        Note by Note: The Making of Steinway L1037 (2007)
4        Title II kills investment? Comcast and other I...
                               ...
20093    How Purism Avoids Intels Active Management Tec...
20094            YC Application Translated and Broken Down
20095    Microkernels are slow and Elvis didn't do no d...
20096                        How Product Hunt really works
20097    RoboBrowser: Your friendly neighborhood web sc...
Name: title, Length: 20098, dtype: object

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20098 entries, 0 to 20097
Data columns (total 7 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id            20098 non-null  int64
 1   title         20098 non-null  object
 2   url           17658 non-null  object
 3   num_points    20098 non-null  int64
 4   num_comments  20098 non-null  int64
 5   author        20098 non-null  object
 6   created_at    20098 non-null  object
dtypes: int64(3), object(4)
memory usage: 1.1+ MB

In [14]:
df.columns

Index(['id', 'title', 'url', 'num_points', 'num_comments', 'author',
       'created_at'],
      dtype='object')

In [16]:
print(df.shape)

(20098, 7)

In [26]:
filtered = df[df['title'].str.contains("Python")]
filtered

,id,title,url,num_points,num_comments,author,created_at
102,10974870,From Python to Lua: Why We Switched,https://www.distelli.com/blog/using-lua-for-ou...,243,188,chase202,1/26/2016 18:17
103,11244541,Ubuntu 16.04 LTS to Ship Without Python 2,http://news.softpedia.com/news/ubuntu-16-04-lt...,2,1,_snydly,3/8/2016 10:39
144,10963528,Create a GUI Application Using Qt and Python i...,http://digitalpeer.com/s/c63e,21,1,zoodle,1/24/2016 19:01
196,10716331,How I Solved GCHQ's Xmas Card with Python and ...,http://matthewearl.github.io/2015/12/10/gchq-x...,6,1,kipi,12/11/2015 10:38
436,11895088,"Unikernel Power Comes to Java, Node.js, Go, an...",http://www.infoworld.com/article/3082051/open-...,3,1,syslandscape,6/13/2016 16:23
...,...,...,...,...,...,...,...
19596,12061177,David Beazley Python Concurrency from the Gro...,https://www.youtube.com/watch?v=MCs5OvhV9S4,2,1,bakery2k,7/9/2016 13:05
19851,10988468,Ask HN: How to automate Python apps deployment?,NaN,4,18,aalhour,1/28/2016 14:55
19861,11738470,Moving Away from Python 2,https://asmeurer.github.io/blog/posts/moving-a...,227,275,ngoldbaum,5/20/2016 15:14
19979,12524656,Python vs. Julia Observations,https://medium.com/@Jernfrost/python-vs-julia-...,2,1,blacksmythe,9/18/2016 9:54
19997,11735438,Show HN: Decorating: Animated pulsed for your ...,https://github.com/ryukinix/decorating,3,1,lerax,5/20/2016 3:48

In [27]:
filtered2 = df[df['title'].str.contains('JavaScript')]
filtered2

,id,title,url,num_points,num_comments,author,created_at
267,12352636,Show HN: Hire JavaScript - Top JavaScript Talent,https://www.hirejs.com/,1,1,eibrahim,8/24/2016 15:16
811,10741251,Ask HN: Are there any projects or compilers wh...,NaN,1,2,ggonweb,12/15/2015 23:26
1045,11343334,"If you write JavaScript tools or libraries, bu...",https://medium.com/@Rich_Harris/how-to-not-bre...,48,19,callumlocke,3/23/2016 10:54
1092,10422726,Rollup.js: A next-generation JavaScript module...,http://rollupjs.org,57,17,dmmalam,10/21/2015 0:02
1161,12461624,V8 JavaScript Engine: V8 Release 5.4,http://v8project.blogspot.com/2016/09/v8-relea...,126,19,okket,9/9/2016 12:46
...,...,...,...,...,...,...,...
19348,11448301,"Fotorama, a responsive JavaScript photo gallery",http://fotorama.io/,1,1,alexkon,4/7/2016 15:59
19547,12105148,Another Kind of JavaScript Fatigue,http://chrismm.com/blog/the-other-kind-of-java...,9,2,JacksCracked,7/16/2016 3:44
19609,12203508,Lonely programmer detective uncovers the Mozil...,http://stackoverflow.com/a/38677222/984780,29,8,luisperezphd,8/1/2016 16:07
19884,12552131,Ask HN: Best Practices for CSS in a Modern Jav...,NaN,6,6,xwvvvvwx,9/21/2016 20:53
20068,12149183,Show HN: Parse recipe ingredients using JavaSc...,https://github.com/herkyl/ingredients-parser,6,2,zongitsrinzler,7/23/2016 11:35